name: scfoundation
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10.11
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pip
  - pip:
      - packaging
      - ipykernel
      - pandas
      - anndata
      - scanpy
      - matplotlib
      - numpy==1.24.4
      - torchtext==0.14.0
      - scib
      - torch-geometric==2.5.3
      - dcor==0.6
